(async function(){
 const checks=[],wait=()=>new Promise(r=>setTimeout(r,220));
 function assert(ok,name){if(!ok)throw Error(name);checks.push(name);}
 try {
  const all=document.querySelector('[data-f="all"]');all.click();await wait();
  assert(document.title==='Управление процессами и проектами','new book title');
  assert(document.querySelectorAll('.bank-question').length===100,'exactly 100 questions');
  assert(document.querySelectorAll('.answer-variant').length===300,'300 full answer variants');
  assert(document.querySelectorAll('.sd-case').length===7,'seven merged cases');
  const q=document.getElementById('bank-q-1');
  window.bookNavigateTo(q.id,true);await wait();await wait();
  assert(q.open,'deep link opens question');
  q.querySelector('[data-answer-mode="pm"]').click();
  assert(!q.querySelector('[data-answer-variant="pm"]').hidden && q.querySelector('[data-answer-variant="deep"]').hidden,'PMBOK tab filters answer');
  q.querySelector('[data-answer-mode="deep"]').click();await wait();
  assert(localStorage.getItem('ya-answer-bank-q-1')==='deep','answer mode persisted');
  const paragraph=q.querySelector('[data-answer-variant="deep"] p');
  const range=document.createRange();range.selectNodeContents(paragraph);getSelection().removeAllRanges();getSelection().addRange(range);
  const payload=window.bookSaved.payload();
  assert(payload && payload.topicID==='t-a-3','new answer supports Saved selection');
  const snapshot=window.bookAudio.extractTopic('t-a-3');
  const block=snapshot.blocks.find(b=>b.id===payload.anchor);
  assert(block && block.text.includes(payload.text.slice(0,40)),'selected paragraph shares TTS semantic ID');
  assert(snapshot.blocks.some(b=>b.text.includes(q.querySelector('.qt').textContent)),'question prompt included in speech');
  const pm=q.querySelector('[data-answer-variant="pm"] p').textContent.trim();
  assert(!snapshot.blocks.some(b=>b.text===pm),'inactive answer excluded from speech');
  getSelection().removeAllRanges();
  q.querySelector('[data-answer-mode="pm"]').click();
  assert(await window.bookSaved.openSource(payload)==='anchor','saved source reveals inactive answer');
  assert(!q.querySelector('[data-answer-variant="deep"]').hidden,'Saved restores correct variant');
  document.querySelector('[data-f="junior"]').click();await wait();
  assert(getComputedStyle(q).display!=='none','ungraded bank remains visible for Junior');
  document.querySelector('[data-f="head"]').click();await wait();
  assert(getComputedStyle(q).display!=='none','ungraded bank remains visible for Head');
  all.click();await wait();
  const q100=document.getElementById('bank-q-100');
  const deep=q100.querySelector('[data-answer-variant="deep"]');
  const query=Array.from(deep.querySelectorAll('p')).find(p=>p.textContent.length>120).textContent.trim();
  document.getElementById('burger').click();
  const search=document.getElementById('tocSearch');search.value=query;search.dispatchEvent(new Event('input'));
  const hit=document.querySelector('#contentSearchResults a[href="#bank-q-100-deep"]');
  assert(hit,'global search finds full text inside closed detailed answer');
  hit.click();await wait();await wait();
  assert(q100.open && !deep.hidden,'search result opens matching answer');
  assert(!document.body.classList.contains('side-open'),'search result closes menu');
  search.value='';search.dispatchEvent(new Event('input'));
  const closedBefore=Array.from(document.querySelectorAll('details')).filter(d=>!d.open).length;
  window.dispatchEvent(new Event('beforeprint'));
  assert(Array.from(document.querySelectorAll('details')).every(d=>d.open),'printing expands answers');
  window.dispatchEvent(new Event('afterprint'));await wait();
  assert(Array.from(document.querySelectorAll('details')).filter(d=>!d.open).length===closedBefore,'printing restores disclosure state');
  window.bookNavigateTo('sd-architecture-payments',true);await wait();await wait();
  const scroller=document.querySelector('#sd-architecture-payments .diagram-scroll');
  assert(scroller.scrollWidth>scroller.clientWidth || innerWidth>820,'diagram scroll is local on mobile');
  assert(document.documentElement.scrollWidth<=innerWidth,'diagrams do not overflow page');
  assert(document.querySelectorAll('.system-diagram svg[viewBox]').length===14,'offline responsive SVG diagrams');
  const diagramSpeech=window.bookAudio.extractTopic('t-11-4').blocks.map(b=>b.text).join(' ');
  assert(diagramSpeech.includes('Клиент входит через шлюз'),'diagram has spoken text description');
  assert(!diagramSpeech.includes('Сервис — скруглённый блок'),'visual legends excluded from speech');
  window.webkit.messageHandlers.result.postMessage({ok:true,checks});
 } catch(e){window.webkit.messageHandlers.result.postMessage({ok:false,error:String(e),checks});}
})();
