import Foundation

/// Neural-only IT pronunciations. Apple speech rules remain unchanged.
enum TechnicalLexicon {
    static let additions:[String:String] = [
        "XYZ":"экс уай зед", "zebra":"зебра", "plan":"план", "fail-over":"фейловер",
        "scope":"скоуп",
        "spike":"спайк",
        "retry":"ретрай",
        "timeout":"таймаут",
        "failover":"фейловер",
        "fallback":"фолбэк",
        "cache":"кэш",
        "queue":"кью",
        "batch":"батч",
        "token":"токен",
        "prompt":"промпт",
        "bug":"баг",
        "fix":"фикс",
        "flag":"флаг",
        "flags":"флаги",
        "data":"дата",
        "code":"код",
        "mode":"мод",
        "head":"хед",
        "lead":"лид",
        "middle":"мидл",
        "senior":"сеньор",
        "junior":"джуниор",
        "quality":"кволити",
        "change":"чейндж",
        "review":"ревью",
        "retention":"ретеншн",
        "guardrail":"гардрейл",
        "scrum":"скрам",
        "roadmap":"роудмап",
        "mock":"мок",
        "source":"сорс",
        "cycle":"сайкл",
        "check":"чек",
        "velocity":"велосити",
        "mortem":"мортем",
        "flaky":"флейки",
        "blameless":"блеймлесс",
        "kanban":"канбан",
        "planning":"плэнинг",
        "baseline":"бейслайн",
        "request":"реквест",
        "agile":"эджайл",
        "design":"дизайн",
        "runbook":"ранбук",
        "error":"эррор",
        "grep":"греп",
        "cutover":"катовер",
        "topologies":"тополоджис",
        "env":"энв",
        "gitflow":"гитфлоу",
        "dict":"дикт",
        "eval":"эвал",
        "var":"вар",
        "observability":"обзервабилити",
        "idempotency":"идемпотенси",
        "onboarding":"онбординг",
        "rebase":"ребейз",
        "microservices":"майкросервисес",
        "grpc":"джи ар пи си",
        "mlops":"эм эл опс",
        "genai":"джен эй ай",
        "wip":"вип",
        "rice":"райс",
        "safe":"сейф",
        "batna":"батна",
        "swot":"свот",
        "adkar":"адкар",
        "capex":"капекс",
        "opex":"опекс",
        "avg":"эверидж",
        "awk":"ок",
        "uniq":"юник",
        "sev":"сев",
        "TPM":"ти пи эм",
        "DM":"ди эм",
        "CTO":"си ти оу",
        "PMO":"пи эм оу",
        "CPO":"си пи оу",
        "SDLC":"эс ди эл си",
        "ML":"эм эл",
        "KR":"кей ар",
        "WSJF":"дабл ю эс джей эф",
        "ADR":"эй ди ар",
        "NPV":"эн пи ви",
        "CFR":"си эф ар",
        "WBS":"дабл ю би эс",
        "IC":"ай си",
        "RFC":"ар эф си",
        "CFD":"си эф ди",
        "QR":"кью ар",
        "CR":"си ар",
        "MTTR":"эм ти ти ар",
        "SBI":"эс би ай",
        "JTBD":"джей ти би ди",
        "TCO":"ти си оу",
        "LLM":"эл эл эм",
        "CTE":"си ти и",
        "NSM":"эн эс эм",
        "SAST":"эс эй эс ти",
        "PID":"пи ай ди",
        "LTV":"эл ти ви",
        "DF":"ди эф",
        "PS":"пи эс",
        "CJM":"си джей эм",
        "AARRR":"эй эй ар ар ар",
        "SLE":"эс эл и",
        "NPS":"эн пи эс",
        "TTR":"ти ти ар",
        "TTD":"ти ти ди",
        "TTM":"ти ти эм",
        "QPS":"кью пи эс",
        "SCA":"эс си эй",
        "TLS":"ти эл эс",
        "VSM":"ви эс эм",
        "IAC":"ай эй си",
        "SM":"эс эм",
        "RN":"ар эн",
        "RSU":"ар эс ю",
        "PCI":"пи си ай",
        "PMBOK":"пи эм би оу кей",
        "ARPU":"эй ар пи ю",
        "TTL":"ти ти эл",
        "AUC":"эй ю си",
        "ISO":"ай эс оу",
        "QG":"кью джи",
        "TC":"ти си",
        "POC":"пи оу си",
        "DAST":"ди эй эс ти",
        "ANR":"эй эн ар",
        "CF":"си эф",
        "EAC":"и эй си",
        "PD":"пи ди",
        "SSH":"эс эс эйч",
        "RH":"ар эйч",
        "RM":"ар эм",
        "ID":"ай ди",
        "CEO":"си и оу",
        "PM":"пи эм",
        "HR":"эйч ар",
        "CIO":"си ай оу",
        "PR":"пи ар",
        "AI":"эй ай",
        "framework":"фреймворк", "feature":"фича", "deployment":"деплоймент", "delivery":"деливери", "monitoring":"мониторинг", "streaming":"стриминг",
        "frontend":"фронтенд", "dashboard":"дашборд", "workflow":"воркфлоу", "feedback":"фидбэк", "performance":"перформанс", "throughput":"трупут", "latency":"латенси", "rollback":"ролбэк", "hotfix":"хотфикс", "refactoring":"рефакторинг", "sprint":"спринт", "backlog":"бэклог", "product":"продакт", "manager":"менеджер", "team":"тим", "cloud":"клауд", "server":"сервер", "client":"клиент", "service":"сервис", "testing":"тестинг",
        "TCP":"ти си пи", "IP":"ай пи", "URL":"ю ар эл", "URI":"ю ар ай",
        "NoSQL":"ноу эс кью эль", "YAML":"ямл", "CI":"си ай", "CD":"си ди",
        "SLI":"эс эл ай", "KPI":"кей пи ай", "OKR":"оу кей ар", "MVP":"эм ви пи",
        "A/B":"эй би", "B2B":"би ту би", "B2C":"би ту си", "CRM":"си ар эм", "ERP":"и ар пи",
        "IAM":"ай эм", "SSO":"эс эс оу", "OAuth":"оу аут", "JWT":"джей дабл ю ти",
        "SDK":"эс ди кей", "CLI":"си эл ай", "IDE":"ай ди и", "JVM":"джей ви эм",
        "DB":"ди би", "DBMS":"ди би эм эс", "ETL":"и ти эл", "ELT":"и эл ти",
        "CDC":"си ди си", "OLTP":"оу эл ти пи", "OLAP":"олап", "QA":"кью эй",
        "DevOps":"девопс", "SRE":"эс ар и", "RTO":"ар ти оу", "RPO":"ар пи оу",
        "Postgres":"постгрес", "Docker Compose":"докер компоуз", "Docker":"докер",
        "Git":"гит", "GitLab":"гитлаб", "GitHub":"гитхаб", "Java":"джава", "Kotlin":"котлин",
        "Swift":"свифт", "Python":"пайтон", "JavaScript":"джаваскрипт", "TypeScript":"тайпскрипт",
        "React":"реакт", "Redis":"редис", "MongoDB":"монго ди би", "Oracle":"оракл", "Linux":"линукс",
        "nginx":"энджин икс", "Grafana":"графана", "Prometheus":"прометеус", "Jira":"джира",
        "Confluence":"конфлюенс", "Jenkins":"дженкинс", "RabbitMQ":"рэббит эм кью", "Debezium":"дебезиум",
        "iOS":"ай оу эс", "CPU":"си пи ю", "RAM":"оперативной памяти", "RPS":"ар пи эс", "TPS":"ти пи эс",
        "WAL":"вал", "MAU":"эм эй ю", "DAU":"ди эй ю", "Conversion":"конверсия",
        "Lead time":"лид тайм", "merge request":"мёрдж реквест", "pull request":"пул реквест",
        "pipeline":"пайплайн", "release":"релиз", "deploy":"деплой", "commit":"коммит",
        "GB":"гигабайт", "MB":"мегабайт", "KB":"килобайт", "TB":"терабайт"
    ]
    // The user explicitly requested the IT pronunciation instead of Apple's translation.
    static let entries = SpeechTextProcessor.pronunciations.merging(additions) { original,_ in original }
        .merging(["rollback":"ролбэк"]) { _, neural in neural }
    static let lowerEntries = Dictionary(uniqueKeysWithValues: entries.map { ($0.key.lowercased(), $0.value) })
    static let letters:[String:String] = ["a":"эй","b":"би","c":"си","d":"ди","e":"и","f":"эф","g":"джи","h":"эйч","i":"ай","j":"джей","k":"кей","l":"эл","m":"эм","n":"эн","o":"оу","p":"пи","q":"кью","r":"ар","s":"эс","t":"ти","u":"ю","v":"ви","w":"дабл ю","x":"экс","y":"уай","z":"зед"]
}
